# Generated by Django 5.2.7 on 2025-11-17 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas_como_estudiante', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas_como_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('estudiante', 'tutor')},
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_universitario', models.CharField(max_length=15, unique=True, verbose_name='Rol Universitario')),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('TUTOR', 'Tutor/a')], max_length=15, verbose_name='Rol')),
                ('nombre_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Social')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('carrera', models.CharField(blank=True, max_length=100, null=True, verbose_name='Carrera')),
                ('año_estudio', models.IntegerField(blank=True, null=True)),
                ('ramo_tutorizado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ramo de Tutoría/Interés')),
                ('tutor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'TUTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_asignados', to='inicio.perfil', verbose_name='Tutor Asignado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room_tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_de_sala', to='inicio.room', verbose_name='Sala Privada con Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='inicio.room')),
            ],
            options={
                'verbose_name_plural': 'Mensajes',
                'ordering': ('timestamp',),
            },
        ),
    ]
