# Generated by Django 5.2.7 on 2025-10-26 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_universitario', models.CharField(max_length=15, unique=True, verbose_name='Rol Universitario')),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('TUTOR', 'Tutor/a')], max_length=15, verbose_name='Rol')),
                ('nombre_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Social')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('carrera', models.CharField(blank=True, max_length=100, null=True, verbose_name='Carrera')),
                ('año_estudio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Año de Estudio')),
                ('tutor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'TUTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_asignados', to='inicio.perfil', verbose_name='Tutor Asignado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
